"""
Vector store tools — ChromaDB query and upsert operations.

Embeddings are generated via Gemini's text-embedding-004 model.
ChromaDB is configured with a custom Gemini embedding function so
all upserts and queries use the same embedding space.
"""

from __future__ import annotations

import chromadb
from chromadb.api.types import EmbeddingFunction, Documents, Embeddings
from google import genai
import structlog

from agents.config import settings

logger = structlog.get_logger()

_client: chromadb.HttpClient | None = None
_embedding_fn: EmbeddingFunction | None = None
COLLECTION_NAME = "artemis_knowledge_base"


class GenAIEmbeddingFunction(EmbeddingFunction[Documents]):
    """Custom ChromaDB Embedding Function using the new google-genai SDK."""
    def __init__(self, api_key: str, model_name: str = "models/gemini-embedding-001"):
        self.client = genai.Client(api_key=api_key)
        self.model_name = model_name

    def __call__(self, input: Documents) -> Embeddings:
        # Generate embeddings for a list of strings
        response = self.client.models.embed_content(
            model=self.model_name,
            contents=list(input)
        )
        return [emb.values for emb in response.embeddings]


def get_embedding_function() -> EmbeddingFunction:
    """Get the Gemini embedding function for ChromaDB."""
    global _embedding_fn
    if _embedding_fn is None:
        _embedding_fn = GenAIEmbeddingFunction(
            api_key=settings.google_api_key,
            model_name="models/gemini-embedding-001",
        )
    return _embedding_fn


def get_chroma_client() -> chromadb.HttpClient:
    """Lazy-initialize and return the ChromaDB HTTP client."""
    global _client
    if _client is None:
        _client = chromadb.HttpClient(
            host=settings.chroma_host,
            port=settings.chroma_port,
        )
    return _client


def get_collection() -> chromadb.Collection:
    """Get or create the main knowledge base collection with Gemini embeddings."""
    client = get_chroma_client()
    return client.get_or_create_collection(
        name=COLLECTION_NAME,
        metadata={"hnsw:space": "cosine"},
        embedding_function=get_embedding_function(),
    )


async def query_knowledge_base(
    query_text: str,
    n_results: int = 10,
    where_filter: dict | None = None,
) -> list[dict]:
    """Query the vector store for relevant chunks using Gemini embeddings.

    Args:
        query_text: The text to find similar chunks for.
        n_results: Number of results to return.
        where_filter: Optional ChromaDB where filter (e.g., {"source": "github"}).

    Returns:
        List of dicts with keys: id, document, metadata, distance.
    """
    collection = get_collection()

    query_params: dict = {
        "query_texts": [query_text],
        "n_results": n_results,
    }
    if where_filter:
        query_params["where"] = where_filter

    results = collection.query(**query_params)

    documents = []
    if results and results["documents"]:
        for i, doc in enumerate(results["documents"][0]):
            documents.append({
                "id": results["ids"][0][i] if results["ids"] else None,
                "document": doc,
                "metadata": results["metadatas"][0][i] if results["metadatas"] else {},
                "distance": results["distances"][0][i] if results["distances"] else None,
            })

    logger.info("vector.query", query_length=len(query_text), results=len(documents))
    return documents


async def upsert_chunks(
    ids: list[str],
    documents: list[str],
    metadatas: list[dict],
) -> None:
    """Add or update document chunks in the vector store.

    Embeddings are automatically generated by the Gemini embedding
    function configured on the collection.

    Args:
        ids: Unique IDs for each chunk.
        documents: The text content of each chunk.
        metadatas: Metadata dicts (source, timestamp, content_type, tags).
    """
    collection = get_collection()
    collection.upsert(
        ids=ids,
        documents=documents,
        metadatas=metadatas,
    )
    logger.info("vector.upsert", count=len(ids))


async def get_collection_stats() -> dict:
    """Get basic stats about the knowledge base collection."""
    collection = get_collection()
    count = collection.count()
    return {"collection": COLLECTION_NAME, "document_count": count}
